/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package productivityTracker;

/**
 *
 * @author QAISER AFTAB
 */
public class timetable extends javax.swing.JFrame {

    /**
     * Creates new form timetable
     */
    public timetable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cell2 = new oops.Cell();
        Mon = new oops.Cell();
        cell3 = new oops.Cell();
        cell4 = new oops.Cell();
        cell5 = new oops.Cell();
        cell6 = new oops.Cell();
        cell7 = new oops.Cell();
        cell8 = new oops.Cell();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField129 = new javax.swing.JTextField();
        jTextField130 = new javax.swing.JTextField();
        jTextField131 = new javax.swing.JTextField();
        jTextField132 = new javax.swing.JTextField();
        cell15 = new oops.Cell();
        jTextField120 = new javax.swing.JTextField();
        jTextField116 = new javax.swing.JTextField();
        jTextField115 = new javax.swing.JTextField();
        jTextField117 = new javax.swing.JTextField();
        jTextField118 = new javax.swing.JTextField();
        jTextField119 = new javax.swing.JTextField();
        cell22 = new oops.Cell();
        jTextField111 = new javax.swing.JTextField();
        jTextField109 = new javax.swing.JTextField();
        jTextField113 = new javax.swing.JTextField();
        jTextField114 = new javax.swing.JTextField();
        jTextField110 = new javax.swing.JTextField();
        jTextField112 = new javax.swing.JTextField();
        cell29 = new oops.Cell();
        jTextField103 = new javax.swing.JTextField();
        jTextField108 = new javax.swing.JTextField();
        jTextField105 = new javax.swing.JTextField();
        jTextField104 = new javax.swing.JTextField();
        jTextField106 = new javax.swing.JTextField();
        jTextField107 = new javax.swing.JTextField();
        cell36 = new oops.Cell();
        jTextField122 = new javax.swing.JTextField();
        jTextField126 = new javax.swing.JTextField();
        jTextField121 = new javax.swing.JTextField();
        jTextField124 = new javax.swing.JTextField();
        jTextField125 = new javax.swing.JTextField();
        jTextField123 = new javax.swing.JTextField();
        cell43 = new oops.Cell();
        jTextField97 = new javax.swing.JTextField();
        jTextField99 = new javax.swing.JTextField();
        jTextField101 = new javax.swing.JTextField();
        jTextField98 = new javax.swing.JTextField();
        jTextField100 = new javax.swing.JTextField();
        jTextField102 = new javax.swing.JTextField();
        cell50 = new oops.Cell();
        jTextField91 = new javax.swing.JTextField();
        jTextField96 = new javax.swing.JTextField();
        jTextField94 = new javax.swing.JTextField();
        jTextField93 = new javax.swing.JTextField();
        jTextField92 = new javax.swing.JTextField();
        jTextField95 = new javax.swing.JTextField();
        cell57 = new oops.Cell();
        jTextField88 = new javax.swing.JTextField();
        jTextField90 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jTextField86 = new javax.swing.JTextField();
        jTextField87 = new javax.swing.JTextField();
        jTextField89 = new javax.swing.JTextField();
        cell64 = new oops.Cell();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();
        jTextField83 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jTextField84 = new javax.swing.JTextField();
        cell71 = new oops.Cell();
        jTextField77 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        cell78 = new oops.Cell();
        jTextField69 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(13, 7));

        cell2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cell2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell2ActionPerformed(evt);
            }
        });
        jPanel2.add(cell2);

        Mon.setText("Mon");
        Mon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(Mon);

        cell3.setText("Tue");
        cell3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell3);

        cell4.setText("Wed");
        cell4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell4);

        cell5.setText("Thu");
        cell5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell5);

        cell6.setText("Fri");
        cell6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cell6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell6ActionPerformed(evt);
            }
        });
        jPanel2.add(cell6);

        cell7.setText("Sat");
        cell7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell7);

        cell8.setText("8");
        cell8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell8);

        jTextField1.setText("Enter Class");
        jPanel2.add(jTextField1);

        jTextField2.setText("Enter Class");
        jPanel2.add(jTextField2);

        jTextField129.setText("Enter Class");
        jPanel2.add(jTextField129);

        jTextField130.setText("Enter Class");
        jPanel2.add(jTextField130);

        jTextField131.setText("Enter Class");
        jPanel2.add(jTextField131);

        jTextField132.setText("Enter Class");
        jPanel2.add(jTextField132);

        cell15.setText("9");
        cell15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell15);

        jTextField120.setText("Enter Class");
        jPanel2.add(jTextField120);

        jTextField116.setText("Enter Class");
        jPanel2.add(jTextField116);

        jTextField115.setText("Enter Class");
        jPanel2.add(jTextField115);

        jTextField117.setText("Enter Class");
        jPanel2.add(jTextField117);

        jTextField118.setText("Enter Class");
        jPanel2.add(jTextField118);

        jTextField119.setText("Enter Class");
        jPanel2.add(jTextField119);

        cell22.setText("10");
        cell22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell22);

        jTextField111.setText("Enter Class");
        jPanel2.add(jTextField111);

        jTextField109.setText("Enter Class");
        jPanel2.add(jTextField109);

        jTextField113.setText("Enter Class");
        jPanel2.add(jTextField113);

        jTextField114.setText("Enter Class");
        jPanel2.add(jTextField114);

        jTextField110.setText("Enter Class");
        jPanel2.add(jTextField110);

        jTextField112.setText("Enter Class");
        jPanel2.add(jTextField112);

        cell29.setText("11");
        cell29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell29);

        jTextField103.setText("Enter Class");
        jPanel2.add(jTextField103);

        jTextField108.setText("Enter Class");
        jPanel2.add(jTextField108);

        jTextField105.setText("Enter Class");
        jPanel2.add(jTextField105);

        jTextField104.setText("Enter Class");
        jPanel2.add(jTextField104);

        jTextField106.setText("Enter Class");
        jPanel2.add(jTextField106);

        jTextField107.setText("Enter Class");
        jPanel2.add(jTextField107);

        cell36.setText("12");
        cell36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cell36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cell36ActionPerformed(evt);
            }
        });
        jPanel2.add(cell36);

        jTextField122.setText("Enter Class");
        jPanel2.add(jTextField122);

        jTextField126.setText("Enter Class");
        jPanel2.add(jTextField126);

        jTextField121.setText("Enter Class");
        jPanel2.add(jTextField121);

        jTextField124.setText("Enter Class");
        jPanel2.add(jTextField124);

        jTextField125.setText("Enter Class");
        jPanel2.add(jTextField125);

        jTextField123.setText("Enter Class");
        jPanel2.add(jTextField123);

        cell43.setText("13");
        cell43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell43);

        jTextField97.setText("Enter Class");
        jPanel2.add(jTextField97);

        jTextField99.setText("Enter Class");
        jPanel2.add(jTextField99);

        jTextField101.setText("Enter Class");
        jPanel2.add(jTextField101);

        jTextField98.setText("Enter Class");
        jPanel2.add(jTextField98);

        jTextField100.setText("Enter Class");
        jPanel2.add(jTextField100);

        jTextField102.setText("Enter Class");
        jPanel2.add(jTextField102);

        cell50.setText("14");
        cell50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell50);

        jTextField91.setText("Enter Class");
        jPanel2.add(jTextField91);

        jTextField96.setText("Enter Class");
        jPanel2.add(jTextField96);

        jTextField94.setText("Enter Class");
        jPanel2.add(jTextField94);

        jTextField93.setText("Enter Class");
        jPanel2.add(jTextField93);

        jTextField92.setText("Enter Class");
        jPanel2.add(jTextField92);

        jTextField95.setText("Enter Class");
        jPanel2.add(jTextField95);

        cell57.setText("15");
        cell57.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell57);

        jTextField88.setText("Enter Class");
        jPanel2.add(jTextField88);

        jTextField90.setText("Enter Class");
        jPanel2.add(jTextField90);

        jTextField85.setText("Enter Class");
        jPanel2.add(jTextField85);

        jTextField86.setText("Enter Class");
        jPanel2.add(jTextField86);

        jTextField87.setText("Enter Class");
        jPanel2.add(jTextField87);

        jTextField89.setText("Enter Class");
        jPanel2.add(jTextField89);

        cell64.setText("16");
        cell64.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell64);

        jTextField79.setText("Enter Class");
        jPanel2.add(jTextField79);

        jTextField80.setText("Enter Class");
        jPanel2.add(jTextField80);

        jTextField81.setText("Enter Class");
        jPanel2.add(jTextField81);

        jTextField83.setText("Enter Class");
        jPanel2.add(jTextField83);

        jTextField82.setText("Enter Class");
        jPanel2.add(jTextField82);

        jTextField84.setText("Enter Class");
        jPanel2.add(jTextField84);

        cell71.setText("17");
        cell71.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell71);

        jTextField77.setText("Enter Class");
        jPanel2.add(jTextField77);

        jTextField75.setText("Enter Class");
        jPanel2.add(jTextField75);

        jTextField76.setText("Enter Class");
        jPanel2.add(jTextField76);

        jTextField73.setText("Enter Class");
        jPanel2.add(jTextField73);

        jTextField74.setText("Enter Class");
        jPanel2.add(jTextField74);

        jTextField78.setText("Enter Class");
        jPanel2.add(jTextField78);

        cell78.setText("18");
        cell78.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(cell78);

        jTextField69.setText("Enter Class");
        jPanel2.add(jTextField69);

        jTextField68.setText("Enter Class");
        jPanel2.add(jTextField68);

        jTextField67.setText("Enter Class");
        jPanel2.add(jTextField67);

        jTextField70.setText("Enter Class");
        jPanel2.add(jTextField70);

        jTextField71.setText("Enter Class");
        jPanel2.add(jTextField71);

        jTextField72.setText("Enter Class");
        jPanel2.add(jTextField72);

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cell36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell36ActionPerformed

    private void cell6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell6ActionPerformed

    private void cell2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cell2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cell2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private oops.Cell Mon;
    private oops.Cell cell15;
    private oops.Cell cell2;
    private oops.Cell cell22;
    private oops.Cell cell29;
    private oops.Cell cell3;
    private oops.Cell cell36;
    private oops.Cell cell4;
    private oops.Cell cell43;
    private oops.Cell cell5;
    private oops.Cell cell50;
    private oops.Cell cell57;
    private oops.Cell cell6;
    private oops.Cell cell64;
    private oops.Cell cell7;
    private oops.Cell cell71;
    private oops.Cell cell78;
    private oops.Cell cell8;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField100;
    private javax.swing.JTextField jTextField101;
    private javax.swing.JTextField jTextField102;
    private javax.swing.JTextField jTextField103;
    private javax.swing.JTextField jTextField104;
    private javax.swing.JTextField jTextField105;
    private javax.swing.JTextField jTextField106;
    private javax.swing.JTextField jTextField107;
    private javax.swing.JTextField jTextField108;
    private javax.swing.JTextField jTextField109;
    private javax.swing.JTextField jTextField110;
    private javax.swing.JTextField jTextField111;
    private javax.swing.JTextField jTextField112;
    private javax.swing.JTextField jTextField113;
    private javax.swing.JTextField jTextField114;
    private javax.swing.JTextField jTextField115;
    private javax.swing.JTextField jTextField116;
    private javax.swing.JTextField jTextField117;
    private javax.swing.JTextField jTextField118;
    private javax.swing.JTextField jTextField119;
    private javax.swing.JTextField jTextField120;
    private javax.swing.JTextField jTextField121;
    private javax.swing.JTextField jTextField122;
    private javax.swing.JTextField jTextField123;
    private javax.swing.JTextField jTextField124;
    private javax.swing.JTextField jTextField125;
    private javax.swing.JTextField jTextField126;
    private javax.swing.JTextField jTextField129;
    private javax.swing.JTextField jTextField130;
    private javax.swing.JTextField jTextField131;
    private javax.swing.JTextField jTextField132;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField86;
    private javax.swing.JTextField jTextField87;
    private javax.swing.JTextField jTextField88;
    private javax.swing.JTextField jTextField89;
    private javax.swing.JTextField jTextField90;
    private javax.swing.JTextField jTextField91;
    private javax.swing.JTextField jTextField92;
    private javax.swing.JTextField jTextField93;
    private javax.swing.JTextField jTextField94;
    private javax.swing.JTextField jTextField95;
    private javax.swing.JTextField jTextField96;
    private javax.swing.JTextField jTextField97;
    private javax.swing.JTextField jTextField98;
    private javax.swing.JTextField jTextField99;
    // End of variables declaration//GEN-END:variables
}
